# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

# config/_default/languages.yaml

en:
  menu:
    main:
      - name: About
        pageRef: about
        weight: 10
      - name: Games
        pageRef: /games
        weight: 20
      - name: News
        pageRef: /news
        weight: 30
      - name: Contact
        pageRef: /contact
        weight: 40
pt:
  menu:
    main:
      - name: Acerca
        pageRef: /about
        weight: 10
      - name: Jogos
        pageRef: /games
        weight: 20
      - name: Novidades
        pageRef: /news
        weight: 30
      - name: Contacto
        pageRef: /contact
        weight: 40